In [96]:
import pandas as pd
import keras
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense,Activation , Dropout


In [97]:


df = pd.read_csv('NSLkdd_train.txt', names = [ 'duration'
, 'protocol_type' 
, 'service'
, 'flag'
, 'src_bytes' 
, 'dst_bytes' 
, 'land' 
, 'wrong_fragment' 
, 'urgent' 
, 'hot' 
, 'num_failed_logins' 
, 'logged_in' 
, 'num_compromised' 
, 'root_shell' 
, 'su_attempted' 
, 'num_root' 
, 'num_file_creations' 
, 'num_shells' 
, 'num_access_files' 
, 'num_outbound_cmds' 
, 'is_host_login'  
, 'is_guest_login' 
, 'count' 
, 'srv_count' 
, 'serror_rate' 
, 'srv_serror_rate' 
, 'rerror_rate' 
, 'srv_rerror_rate' 
, 'same_srv_rate' 
, 'diff_srv_rate' 
, 'srv_diff_host_rate' 
, 'dst_host_count' 
, 'dst_host_srv_count' 
, 'dst_host_same_srv_rate' 
, 'dst_host_diff_srv_rate' 
, 'dst_host_same_src_port_rate' 
, 'dst_host_srv_diff_host_rate' 
, 'dst_host_serror_rate' 
, 'dst_host_srv_serror_rate' 
, 'dst_host_rerror_rate' 
, 'dst_host_srv_rerror_rate' 
, 'diffic' 
, 'class' ])

In [98]:
df['service'].unique().shape

(65,)

In [99]:
len(df[df['class'] == 'normal'])


6503

In [100]:
len(df[df['class'] == 'Dos'])

4487

In [101]:
len(df[df['class']== 'Probe'])

1072

In [102]:
len(df[df['class']== 'U2R'])


7

In [103]:
len(df[df['class']== 'R2L'])


93

In [104]:
df['protocol_type']= df['protocol_type'].astype('category').cat.codes
df['flag'] = df['flag'].astype('category').cat.codes
df['service'] = df['service'].astype('category').cat.codes

In [105]:
df.head()

duration  protocol_type  service  flag  src_bytes  dst_bytes  land  \
0         0              1       23     9        287       1281     0   
1         0              1       23     9        344       1451     0   
2         0              0       15     9       1032          0     0   
3         0              2       45     9         28          0     0   
4         0              1       23     9        331       1694     0   

   wrong_fragment  urgent  hot   ...    dst_host_same_srv_rate  \
0               0       0    0   ...                      1.00   
1               0       0    0   ...                      1.00   
2               0       0    0   ...                      0.34   
3               3       0    0   ...                      0.17   
4               0       0    0   ...                      1.00   

   dst_host_diff_srv_rate  dst_host_same_src_port_rate  \
0                    0.00                         0.00   
1                    0.00                         0.00   
2                    0.04                         0.34   
3                    0.02                         0.17   
4                    0.00                         0.02   

   dst_host_srv_diff_host_rate  dst_host_serror_rate  \
0                         0.00                  0.00   
1                         0.00                  0.00   
2                         0.00                  0.08   
3                         0.00                  0.00   
4                         0.02                  0.00   

   dst_host_srv_serror_rate  dst_host_rerror_rate  dst_host_srv_rerror_rate  \
0                       0.0                  0.00                      0.00   
1                       0.0                  0.02                      0.02   
2                       0.0                  0.02                      0.00   
3                       0.0                  0.00                      0.00   
4                       0.0                  0.00                      0.00   

   diffic   class  
0      21  normal  
1      21  normal  
2      19     Dos  
3      15     Dos  
4      21  normal  

[5 rows x 43 columns]

In [106]:
y_train = df['class'].astype('category').cat.codes

In [107]:
y_train.unique()

array([4, 0, 1, 3, 2], dtype=int64)

In [108]:
y_train = np_utils.to_categorical(y_train,5)

In [109]:
y_train.shape

(12162, 5)

In [110]:
y_train[2]

array([ 1.,  0.,  0.,  0.,  0.])

In [111]:
del df['class']

In [112]:
x_train = df.values

In [113]:
df_test = pd.read_csv('NSLkdd_test.txt', names = [ 'duration'
, 'protocol_type' 
, 'service'
, 'flag'
, 'src_bytes' 
, 'dst_bytes' 
, 'land' 
, 'wrong_fragment' 
, 'urgent' 
, 'hot' 
, 'num_failed_logins' 
, 'logged_in' 
, 'num_compromised' 
, 'root_shell' 
, 'su_attempted' 
, 'num_root' 
, 'num_file_creations' 
, 'num_shells' 
, 'num_access_files' 
, 'num_outbound_cmds' 
, 'is_host_login'  
, 'is_guest_login' 
, 'count' 
, 'srv_count' 
, 'serror_rate' 
, 'srv_serror_rate' 
, 'rerror_rate' 
, 'srv_rerror_rate' 
, 'same_srv_rate' 
, 'diff_srv_rate' 
, 'srv_diff_host_rate' 
, 'dst_host_count' 
, 'dst_host_srv_count' 
, 'dst_host_same_srv_rate' 
, 'dst_host_diff_srv_rate' 
, 'dst_host_same_src_port_rate' 
, 'dst_host_srv_diff_host_rate' 
, 'dst_host_serror_rate' 
, 'dst_host_srv_serror_rate' 
, 'dst_host_rerror_rate' 
, 'dst_host_srv_rerror_rate' 
, 'diffic' 
, 'class' ])

In [114]:
df_test['protocol_type']= df_test['protocol_type'].astype('category').cat.codes
df_test['flag'] = df_test['flag'].astype('category').cat.codes
df_test['service'] = df_test['service'].astype('category').cat.codes

In [115]:
df_test.head()

duration  protocol_type  service  flag  src_bytes  dst_bytes  land  \
0         0              1       58     5          0          0     0   
1         0              1       25     5          0          0     0   
2         0              1       23     9        195       1274     0   
3         0              1       23     9        333        420     0   
4         0              1       25     5          0          0     0   

   wrong_fragment  urgent  hot   ...    dst_host_same_srv_rate  \
0               0       0    0   ...                      0.06   
1               0       0    0   ...                      0.07   
2               0       0    0   ...                      1.00   
3               0       0    0   ...                      1.00   
4               0       0    0   ...                      0.05   

   dst_host_diff_srv_rate  dst_host_same_src_port_rate  \
0                    0.04                          0.0   
1                    0.05                          0.0   
2                    0.00                          0.0   
3                    0.00                          0.0   
4                    0.07                          0.0   

   dst_host_srv_diff_host_rate  dst_host_serror_rate  \
0                          0.0                   1.0   
1                          0.0                   1.0   
2                          0.0                   0.0   
3                          0.0                   0.0   
4                          0.0                   1.0   

   dst_host_srv_serror_rate  dst_host_rerror_rate  dst_host_srv_rerror_rate  \
0                       1.0                   0.0                       0.0   
1                       1.0                   0.0                       0.0   
2                       0.0                   0.0                       0.0   
3                       0.0                   0.0                       0.0   
4                       1.0                   0.0                       0.0   

   diffic   class  
0      18     Dos  
1      19     Dos  
2      21  normal  
3      21  normal  
4      20     Dos  

[5 rows x 43 columns]

In [116]:
y_test = df_test['class'].astype('category').cat.codes



In [117]:
y_test.unique()

array([0, 4, 1, 2, 3], dtype=int64)

In [118]:
y_test = np_utils.to_categorical(y_test,5)

In [119]:
y_test.shape

(5001, 5)

In [120]:
del df_test['class']

In [121]:
x_test = df_test.values

In [122]:
x_train

array([[  0.00000000e+00,   1.00000000e+00,   2.30000000e+01, ...,
          0.00000000e+00,   0.00000000e+00,   2.10000000e+01],
       [  0.00000000e+00,   1.00000000e+00,   2.30000000e+01, ...,
          2.00000000e-02,   2.00000000e-02,   2.10000000e+01],
       [  0.00000000e+00,   0.00000000e+00,   1.50000000e+01, ...,
          2.00000000e-02,   0.00000000e+00,   1.90000000e+01],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   1.40000000e+01, ...,
          0.00000000e+00,   0.00000000e+00,   1.50000000e+01],
       [  0.00000000e+00,   1.00000000e+00,   2.80000000e+01, ...,
          0.00000000e+00,   0.00000000e+00,   1.80000000e+01],
       [  0.00000000e+00,   1.00000000e+00,   2.30000000e+01, ...,
          0.00000000e+00,   0.00000000e+00,   2.10000000e+01]])

In [123]:
y_train[2363]

array([ 0.,  0.,  1.,  0.,  0.])

In [124]:
x_test

array([[  0.,   1.,  58., ...,   0.,   0.,  18.],
       [  0.,   1.,  25., ...,   0.,   0.,  19.],
       [  0.,   1.,  23., ...,   0.,   0.,  21.],
       ..., 
       [  0.,   1.,  20., ...,   0.,   0.,  13.],
       [  0.,   2.,  12., ...,   0.,   0.,  19.],
       [  0.,   1.,  23., ...,   0.,   0.,  21.]])

In [125]:
y_test[1016]

array([ 0.,  0.,  0.,  1.,  0.])

In [126]:
x_test.shape

(5001, 42)

In [127]:
y_test.shape

(5001, 5)

In [128]:
x_train.shape

(12162, 42)

In [129]:
from keras.callbacks import EarlyStopping 
early_stopping_monitor = EarlyStopping(patience=2) model = Sequential()

model.add(Dense(35, activation = 'relu',  input_dim = 42))
model.add(Dense(22, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
#model.add(Dropout(0.5))
model.add(Dense(5, activation = 'softmax'))

#model.summary()

#model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
#model.fit(x_train, y_train, 
         validation_split = 0.33,batch_size = 32, nb_epoch=10, verbose=1)

#model.predict

#score = model.evaluate(x_test, y_test, verbose=0)
#print(score)

SyntaxError: invalid syntax (<ipython-input-129-d3fdf7d9da01>, line 2)

In [130]:
from keras.models import load_model
from keras.callbacks import EarlyStopping 
#early_stopping_monitor = EarlyStopping(patience=100)
from keras.optimizers import RMSprop 
from keras.callbacks import ModelCheckpoint
opt = RMSprop(lr = 0.0006, decay = 1e-6)


model = Sequential()

model.add(Dense(35, activation = 'sigmoid', input_dim = 42))
model.add(Dense(22, activation = 'sigmoid',))
#model.add(Dense(15, activation = 'sigmoid'))
model.add(Dense(10, activation = 'relu'))
#model.add(Dropout(0.5))
model.add(Dense(5, activation = 'softmax' ))

model.summary()
#model = model.load_weights('weights_rmsprop_99.35.hdf5')

model.compile(loss='categorical_crossentropy',
              optimizer= opt,
              metrics=['accuracy'])
filepath="weights-improvement-{epoch:02d}-{acc:.2f}.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='acc', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]
model.fit(x_train, y_train, 
          batch_size=32,validation_split = 0.33, nb_epoch=200, verbose=1, callbacks = callbacks_list)

#model.predict

score = model.evaluate(x_test, y_test, verbose=2)
print(score)

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
dense_41 (Dense)                 (None, 35)            1505        dense_input_18[0][0]             
____________________________________________________________________________________________________
dense_42 (Dense)                 (None, 22)            792         dense_41[0][0]                   
____________________________________________________________________________________________________
dense_43 (Dense)                 (None, 10)            230         dense_42[0][0]                   
____________________________________________________________________________________________________
dense_44 (Dense)                 (None, 5)             55          dense_43[0][0]                   
Total params: 2,582
Trainable params: 2,582
Non-trainable params: 0
_______________________

KeyboardInterrupt: 

In [ ]:
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)

In [ ]:
from keras.models import model_from_json

#model = model_from_json(open('weights_rmsprop_99.35.json').read())

model = model.load_weights('weights_rmsprop_99.35.hdf5')

model.compile(loss='categorical_crossentropy',
              optimizer= opt1,
              metrics=['accuracy'])

In [ ]:
model.save_weights('weights_rmsprop_99.35.hdf5', overwrite = False)


In [ ]:
y_pred = model.predict(x_test[0:])

In [ ]:
import numpy as np
np.argmax(y_pred, axis =1)

In [ ]:
np.argmax(y_test, axis = 1 )

In [ ]:
import numpy as np

print(confusion_matrix(np.argmax(y_test,axis = 1),np.argmax( y_pred, axis = 1)))

In [138]:

from keras.models import model_from_json
from keras.optimizers import RMSprop
opt = RMSprop(lr = 0.0006, decay = 1e-6)


# load json and create model
json_file = open('best/model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("best/weights-improvement-153-THEBEST-1.00.hdf5")
print("Loaded model from disk")
 
# evaluate loaded model on test data

loaded_model.compile(loss='categorical_crossentropy',
              optimizer= opt,
              metrics=['accuracy'])


#loaded_model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
score = loaded_model.evaluate(x_test, y_test, verbose=0)
print("%s: %.2f%%" % (loaded_model.metrics_names[1], score[1]*100))

Loaded model from disk
acc: 99.32%


In [133]:
y_pred = loaded_model.predict(x_test[0:])

In [134]:
import numpy as np
from sklearn.metrics import confusion_matrix


matrix = confusion_matrix(np.argmax(y_test,axis = 1),np.argmax( y_pred, axis = 1))

In [135]:
classes = ['Dos', 'probe', 'R2L', 'U2R','normal']
np.hstack((matrix, classes))

ValueError: all the input arrays must have same number of dimensions

In [136]:
matrix

array([[1872,    3,    0,    0,   10],
       [   0,  504,    0,    0,    5],
       [   0,    0,   31,    0,    6],
       [   0,    0,    0,    0,    1],
       [   0,    9,    0,    0, 2560]])

In [ ]:
np.insert(matrix, 0, classes)